# Generated by Django 4.2.3 on 2023-08-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
