# Generated by Django 4.2.3 on 2023-08-13 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_taskmodel_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
        ),
    ]
