# Generated by Django 4.2.3 on 2023-08-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_alter_taskmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='slug',
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_title',
            field=models.CharField(max_length=100),
        ),
    ]
